let card = {
    name: document.querySelector("#charNameForm") ,
    charClass: document.querySelector("#charClassForm") ,
    background: document.querySelector("#charBackgroundForm"),
    player_name: document.querySelector("#playerNameForm"),
    race: document.querySelector("#charFormRace") ,
    alignment: document.querySelector("#charAlignmentForm") ,
    xp: document.querySelector("#experiencepoints") , 
    strength: document.querySelector("#Strengthscore"),     
    dexterity: document.querySelector("#Dexterityscore"),
    constitution: document.querySelector("#Constitutionscore"),
    wisdom: document.querySelector("#Wisdomscore"),
    intellect: document.querySelector("#Intelligencescore"),
    charisma: document.querySelector("#Charismascore"),
    strength_save: document.querySelector("#str-save"), 
    strength_save_check: document.querySelector("#str-save-prof"),  
    dex_save: document.querySelector("#dex-save"),
    dex_save_check: document.querySelector("#str-save-check"),
    const_save: document.querySelector("#const-save"),
    const_save_check: document.querySelector("#const-save-check"), 
    wis-save: document.querySelector("#wis-save"),
    wis_save_check: document.querySelector("#wis-save-check"),
    intellect_save: document.querySelector("#int-save"),
    intellect_save_check:document.querySelector("#int-save-check"),
    char_save: document.querySelector("#char-save"),
    char_save_check: document.querySelector("#char-save-check"),
    acrobatics: document.querySelector("#acrobatics"),
    acrobatics_check: document.querySelector("#acrobatics-check"),
    animal: document.querySelector("#animal"),
    animal_check: document.querySelector("#animal-check"),
    arcana: document.querySelector("#arcana"),
    arcana_check: document.querySelector("#arcana-check"),
    athletic: document.querySelector("#athletic"),
    athletic_check: document.querySelector("#athletic-check"), 
    deception: document.querySelector("#deception"),
    deception_check: document.querySelector("#decept-check"), 
    history: document.querySelector("#hist"),
    history_check:  document.querySelector("#hist-check"),
    insight: document.querySelector("#insight"),
    insight_check: document.querySelector("#insight-check"),
    intimidation: document.querySelector("#intimidate"),
    intimidation_check: document.querySelector("#intimidate-check") , 
    investigation: document.querySelector("#investigate"),
    investigation_check: document.querySelector("#investigate-check"),
    medicine:: document.querySelector("#med"),
    medicine_check: document.querySelector("#med-check"),
    nature: document.querySelector("#nature"),
    nature_check: document.querySelector("nature-check"),  
    perception: document.querySelector("#percept"),
    perception_check: document.querySelector("#percept-check"),
    performance: document.querySelector("#perform"),
    performance_check: document.querySelector("#perform-check"),
    persuasion: document.querySelector("#persuade"),
    persuasion_check: document.querySelector("#persuade-check"),
    religion: document.querySelector("#relig"),
    rligion_check: document.querySelector("#relig-check"),  
    sleight_of_hand: document.querySelector("#soh"),
    soh_check: document.querySelector("#soh-check"),
    stealth: document.querySelector("#stealth"),
    stealth_check: document.querySelector("#stealth-check"),
    survival: document.querySelector("#survival"),
    survival_check: document.querySelector("#survival-check"),
    proficiencybonus = document.querySelector("#proficiencybonus"),
    passive_perception: document.querySelector("#passiveperception"),
    proficiencies_and_languages: document.querySelector("#proficiencies_and_languages"),
    armor_class: document.querySelector("#ac"),
    initiative: document.querySelector("#initiative"),
    speed: document.querySelector("#speed"),
    hp: document.querySelector("#hp"),
    currenthp: document.querySelector("#currenthp"),
    temphp: document.querySelector("#temphp"),
    hitDice: document.querySelector("#hitDice"),
    attacks_and_spellcasting: document.querySelector("#attacks_and_spellcasting"),
    equipment: document.querySelector("#equipment"),
    personality: document.querySelector("#personality"),
    ideals: document.querySelector("#ideals"),
    bonds: document.querySelector("#bonds"),
    flaws: document.querySelector("#flaws"),
    features_and_traits: document.querySelector("#features_and_traits")
}